name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      GITHUB_ACTIONS: true
      TEST_BASE_URL: http://localhost:5001
      DB_USER: testuser
      DB_PASS: testpassword
      DB_HOST_ADDRESS: 127.0.0.1
      DB_HOST: 127.0.0.1
      DB_PORT: 3311
      DB_NAME: reef_test
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: reef_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3311:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Print full environment at start
        run: |
          echo "==== FULL ENVIRONMENT DUMP ===="
          env
          echo "==== END ENVIRONMENT DUMP ===="
      - uses: actions/checkout@v4
      - name: Detect environment and set database host
        run: |
          echo "Detecting CI environment..."
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "ACT: $ACT"
          echo "RUNNER_OS: $RUNNER_OS"
          
          if [ "$ACT" = "true" ]; then
            echo "Running in act environment"
            # In act with host networking, MySQL is available on localhost
            echo "DB_HOST_ADDRESS=127.0.0.1" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=3311" >> $GITHUB_ENV
            echo "TEST_BASE_URL=http://localhost:5001" >> $GITHUB_ENV
          else
            echo "Running in real GitHub Actions"
            echo "DB_HOST_ADDRESS=127.0.0.1" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=3311" >> $GITHUB_ENV
            echo "TEST_BASE_URL=http://localhost:5001" >> $GITHUB_ENV
          fi
          
          # Print final values for debugging
          echo "Final DB_HOST_ADDRESS: 127.0.0.1"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps
      - name: Wait for MySQL
        run: |
          echo "Starting MySQL health check..."
          echo "DB_HOST_ADDRESS: $DB_HOST_ADDRESS"
          echo "DB_PORT: $DB_PORT"
          echo "ACT mode: $ACT"
          
          # Quick connection test function
          test_mysql() {
            local host=$1
            local port=$2
            echo "Testing $host:$port..."
            if timeout 3 mysql -h "$host" -P "$port" -u root -proot -e "SELECT 1;" >/dev/null 2>&1; then
              echo "✅ MySQL ready at $host:$port"
              return 0
            fi
            return 1
          }
          
          # Simple retry loop - in host networking mode, MySQL should be at localhost:3311
          CONNECTED=false
          for attempt in $(seq 1 15); do
            echo "=== Attempt $attempt/15 ==="
            
            if test_mysql "$DB_HOST_ADDRESS" "$DB_PORT"; then
              CONNECTED=true
              break
            fi
            
            echo "Waiting 2 seconds before retry..."
            sleep 2
          done
          
          if [ "$CONNECTED" != "true" ]; then
            echo "❌ MySQL not available after 15 attempts"
            echo "=== Final diagnostics ==="
            netstat -tlnp 2>/dev/null | grep ":$DB_PORT " || echo "No process on port $DB_PORT"
            exit 1
          fi
          
          echo "✅ MySQL ready at $DB_HOST_ADDRESS:$DB_PORT"
      - name: Seed test database
        run: |
          mysql -h $DB_HOST_ADDRESS -P $DB_PORT -u root -proot $DB_NAME < tests/seed.sql
      - name: Clear test data before tests (safe)
        run: |
          echo "Safely clearing any existing test data..."
          mysql -h $DB_HOST_ADDRESS -P $DB_PORT -u root -proot -e "
          USE $DB_NAME;
          SET sql_notes = 0;
          DELETE FROM test_results WHERE 1=1;
          DELETE FROM doser_products WHERE name LIKE '%Playwright Test Product%';
          SET sql_notes = 1;
          " 2>/dev/null || echo "Some tables may not exist yet, continuing..."
      - name: Debug all MySQL users
        run: |
          mysql -h $DB_HOST_ADDRESS -P $DB_PORT -u root -proot -e "SELECT user, host FROM mysql.user;"
      - name: Debug MySQL users
        run: |
          mysql -h $DB_HOST_ADDRESS -P $DB_PORT -u root -proot -e "SELECT user, host FROM mysql.user WHERE user='testuser';"
      - name: Print DB env vars before Flask
        run: |
          echo "DB_USER=$DB_USER"
          echo "DB_PASS=$DB_PASS"
          echo "DB_HOST_ADDRESS=$DB_HOST_ADDRESS"
          echo "DB_PORT=$DB_PORT"
          echo "DB_NAME=$DB_NAME"
          env | grep DB_
      - name: Run unit/API tests
        run: |
          export PYTHONPATH=.
          # Set unit test environment - use SQLite for unit tests to avoid DB dependency
          export TESTING=true
          export FLASK_ENV=testing
          export SQLALCHEMY_DATABASE_URI=sqlite:///:memory:
          pytest tests/unit/ -v
      - name: Run E2E tests
        run: |
          # Use port 5001 to match TEST_BASE_URL
          export FLASK_PORT=5001
          echo "Starting Flask server on port $FLASK_PORT..."
          env \
            FLASK_APP=index.py \
            FLASK_ENV=test \
            FLASK_RUN_HOST=0.0.0.0 \
            FLASK_RUN_PORT=$FLASK_PORT \
            FLASK_DEBUG=0 \
            DB_USER=$DB_USER \
            DB_PASS=$DB_PASS \
            DB_HOST_ADDRESS=$DB_HOST_ADDRESS \
            DB_HOST=$DB_HOST \
            DB_PORT=$DB_PORT \
            DB_NAME=$DB_NAME \
            python -m flask run &
          FLASK_PID=$!
          
          # Wait for Flask to start with health check
          echo "Waiting for Flask to start on port $FLASK_PORT..."
          FLASK_READY=false
          for attempt in $(seq 1 30); do
            echo "Flask health check attempt $attempt/30..."
            if curl -s http://localhost:$FLASK_PORT/ >/dev/null 2>&1; then
              echo "✅ Flask server is ready at http://localhost:$FLASK_PORT"
              FLASK_READY=true
              break
            fi
            sleep 1
          done
          
          if [ "$FLASK_READY" != "true" ]; then
            echo "❌ Flask server failed to start after 30 seconds"
            echo "Flask process status:"
            ps aux | grep flask || echo "No Flask processes found"
            echo "Port $FLASK_PORT status:"
            netstat -tlnp 2>/dev/null | grep ":$FLASK_PORT " || echo "No process on port $FLASK_PORT"
            kill $FLASK_PID 2>/dev/null || true
            exit 1
          fi
          
          # Ensure TEST_BASE_URL matches Flask port
          export TEST_BASE_URL=http://localhost:$FLASK_PORT
          echo "Using TEST_BASE_URL: $TEST_BASE_URL"
          
          # Run E2E tests
          export PYTHONPATH=.
          python -m pytest tests/e2e/ -v
          
          # Clean up Flask process
          echo "Stopping Flask server..."
          kill $FLASK_PID 2>/dev/null || true
